### ISSUE TITLE
Chart not rendering inside Side Drawer

### ISSUE THREAD

**Issue by ashishpawar12** [kyndryl-design-system/shidoka-charts#12] opened 2024-02-27 10:23 UTC
**Describe the bug**

I was trying to implement line chart on side drawer. But not able to load chart

**Expected behavior**

Chart should be loaded on side drawer.

**Screenshots**

<img width="1410" alt="image" src="https://github.com/kyndryl-design-system/shidoka-charts/assets/18259137/10d24486-9523-406e-ad93-8444e034d289">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brian-patrick-3** [comment] 2024-02-27 12:56
FYI, I think putting things like charts and tables in the side drawer goes against design guidelines.

However, it does seem like a legitimate bug that the chart doesn't render inside a container initially set to display: none.

**Comment by brian-patrick-3** [comment] 2024-02-27 16:40
This was actually a CSS positioning issue with the Side Drawer component in shidoka-applications. It is resolved in v1.6.2.

**Comment by ashishpawar12** [comment] 2024-02-28 04:21
Hi @brian-patrick-3 , Still this is not working with sample code i have attach. Can you have a look please

**Comment by brian-patrick-3** [comment] 2024-02-28 13:27
Can you create an example in CodeSandbox that reproduces it? I am unable to reproduce in  shidoka-applications@1.6.2

**Comment by ashishpawar12** [comment] 2024-02-29 08:52
@brian-patrick-3 PFB link for codeSandbox
https://codesandbox.io/p/devbox/gifted-ellis-jj8dq2?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A11%2C25&workspaceId=a63da9bb-5496-4111-be41-7fd9d81ab734

**Comment by brian-patrick-3** [comment] 2024-02-29 16:57
The issue is in how you've written your code:

1. Remove `*ngIf="loadChart"` from each `<kd-chart>`. This is the main problem.
2. Remove `(click)="drawerOpen()"` from anchor span. The button to open the drawer is built-in so this is not needed.
3. Remove extraneous wrapper divs: `<div style="height: 500px;">`. Unnecessary.
4. Remove any inline arrays/objects you are passing to `<kd-chart>` props (labels, options, datasets), and use variables instead. Inline array/object type props can cause unnecessary re-renders.
5. On `<kyn-side-drawer>`, `[hideFooter]="true"` can just be `hideFooter` since it will never change.

[Forked working example](https://codesandbox.io/p/devbox/sidedrawerwithchart-forked-5v544j?file=%2Fsrc%2Fapp%2Fapp.component.html)

**Comment by ashishpawar12** [comment] 2024-03-01 04:00
Hi @brian-patrick-3 , Still its not working after doing all the changes suggested by you. Can you please give me access to fork working example. Its a private folder. Need to move out to public. Thanks

https://codesandbox.io/p/devbox/sidedrawerwithchart-jj8dq2?file=%2Fsrc%2Fapp%2Fapp.component.html%3A52%2C21

<img width="1410" alt="image" src="https://github.com/kyndryl-design-system/shidoka-charts/assets/18259137/365c3d14-0a77-47a1-8f50-e56b7b1193cb">

**Comment by brian-patrick-3** [comment] 2024-03-01 04:09
It should be public now I think

**Comment by ashishpawar12** [comment] 2024-03-01 04:19
@brian-patrick-3 Not working on your codesandbox URL too. First chart work for firefox but not for chrome. And 2nd chart is not working in both browser

<img width="1410" alt="image" src="https://github.com/kyndryl-design-system/shidoka-charts/assets/18259137/83cc4c47-e58b-48c2-8fb6-63c872def4c7">

**Comment by brian-patrick-3** [comment] 2024-03-01 04:30
Thanks for the update. I have one more theory to test tomorrow, it may be related to the chartjs deferred plugin.

**Comment by brian-patrick-3** [comment] 2024-03-01 16:53
Removing `chartjs-plugin-deferred` from being included by default seems to have resolved this in `1.1.7`. It's not ideal, but it can still be added manually if anyone needs it.

**Closed by brian-patrick-3** 2024-03-01 16:53 UTC
Labels: bug, released, prioirty: low, size: medium
